version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./db.sqlite:/app/db.sqlite
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      DATABASE_URL: sqlite:///app/db.sqlite
    command: yarn start:prod