### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "joao",
    "password": "12345"
}

### USUARIO
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "username": "teste",
    "password": "12345"
}

###
GET http://localhost:3000/usuario
Authorization: Bearer __

###
GET http://localhost:3000/usuario/z72p9CImguPA2sw-cMkgP

###
PATCH http://localhost:3000/usuario/id
Content-Type: application/json

{
    "nome": "Joao editado",
    "email": "joao@joao.com"
}

###
DELETE http://localhost:3000/usuario/7JKNHnON2UTTY6AyYuDn1